{"tag": "function", "depth": 2, "time": 1642410221.014924, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1642410219.376431, "ret": {"screen": "1642410220982.jpg", "resolution": [720, 1520]}, "end_time": 1642410221.0149}}
{"tag": "info", "depth": 1, "time": 1642410221.016233, "data": {"name": "PocoNoSuchNodeException", "traceback": "Traceback (most recent call last):\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 26, in wrapped\n    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 681, in wait_for_appearance\n    raise PocoTargetTimeout('appearance', self)\npoco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of \"UIObjectProxy of \"com.keerby.formatfactory:id/imageView\"\"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/tengzhan/Desktop/test/Base/PublicFunction.py\", line 19, in inner\n    f = func(self, *args, **kwargs)\n  File \"/Users/tengzhan/Desktop/test/TestCase/skyvpn/android/test_factory.py\", line 19, in test_video\n    self.poco(\"com.keerby.formatfactory:id/imageView\").click()  # +\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 29, in wrapped\n    raise e\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 23, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 332, in click\n    pos_in_percentage = self.get_position(focus)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 72, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 613, in get_position\n    pos = list(map(float, self.attr('pos')))\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 39, in wrapped\n    return func(self, *args, **kwargs)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 734, in attr\n    nodes = self._do_query(multiple=False)\n  File \"/Users/tengzhan/Desktop/test/venv/lib/python3.8/site-packages/poco/proxy.py\", line 874, in _do_query\n    raise PocoNoSuchNodeException(self)\npoco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of \"com.keerby.formatfactory:id/imageView\"\n"}}
{"tag": "function", "depth": 1, "time": 1642410221.210569, "data": {"name": "stop_app", "call_args": {"package": "me.skyvpn.app"}, "start_time": 1642410221.043408, "ret": null, "end_time": 1642410221.2105129}}
{"tag": "function", "depth": 1, "time": 1642410225.216306, "data": {"name": "sleep", "call_args": {"secs": 4}, "start_time": 1642410221.210814, "ret": null, "end_time": 1642410225.216176}}
